#!/usr/bin/env python3
"""
Send summary email of episodes processed today
"""
import sqlite3
import smtplib
import os
from datetime import datetime, date
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_todays_summary():
    """Send email summary of episodes processed today"""
    print("📧 SENDING TODAY'S EPISODE SUMMARY...")
    
    db_path = 'podcast_app_v2.db'
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Get episodes added today
    cursor.execute('''
        SELECT p.name, e.title, e.publish_date, LENGTH(e.transcript) as transcript_length, e.created_at
        FROM episodes e 
        JOIN podcasts p ON e.podcast_id = p.id 
        WHERE DATE(e.created_at) = DATE('now') 
        ORDER BY e.created_at DESC
    ''')
    
    todays_episodes = cursor.fetchall()
    conn.close()
    
    if not todays_episodes:
        print("   📭 No episodes processed today")
        return
    
    # Prepare email content
    sender_email = os.getenv('EMAIL_USER', 'aipodcastdigest@gmail.com')
    sender_password = os.getenv('EMAIL_PASSWORD')
    recipient_email = 'hwalker146@outlook.com'
    
    if not sender_password:
        print("   ❌ Email password not configured")
        return
    
    # Create email
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = f"🎧 Daily Podcast Summary - {date.today().strftime('%Y-%m-%d')} - {len(todays_episodes)} Episodes"
    
    # Build email body
    body = f"""🎧 DAILY PODCAST PROCESSING SUMMARY

Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

📊 STATUS: {len(todays_episodes)} episodes successfully processed today

"""
    
    for podcast_name, title, publish_date, transcript_length, created_at in todays_episodes:
        publish_date_short = publish_date[:10] if publish_date else 'Unknown'
        body += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎧 {podcast_name}
📅 Published: {publish_date_short}
📝 Title: {title}
📊 Transcript: {transcript_length:,} characters
⏰ Processed: {created_at.split('T')[1][:8]} UTC

"""
    
    body += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ PERFORMANCE METRICS:
• Total episodes processed: {len(todays_episodes)}
• Total transcript characters: {sum(ep[3] for ep in todays_episodes):,}
• Average episode length: {sum(ep[3] for ep in todays_episodes) // len(todays_episodes):,} characters

🤖 All episodes have been:
✅ Downloaded and transcribed with OpenAI Whisper
✅ Saved to database with full metadata
✅ Added to master transcript files

🔧 Recent optimizations:
• Parallel processing (3 workers)
• Audio compression for faster transcription
• 4-hour timeout prevents failures
• Improved episode detection logic

🤖 Generated by unified automation system
"""
    
    msg.attach(MIMEText(body, 'plain'))
    
    # Send email
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient_email, msg.as_string())
        server.quit()
        
        print(f"   ✅ Summary email sent to {recipient_email}")
        print(f"   📊 {len(todays_episodes)} episodes summarized")
        
    except Exception as e:
        print(f"   ❌ Email failed: {e}")

if __name__ == "__main__":
    send_todays_summary()