#!/usr/bin/env python3
"""
Markdown to PDF Converter
Converts markdown files generated by the podcast automation system to PDF format
"""
import os
import sys
from pathlib import Path
import argparse
from datetime import datetime
import subprocess
import tempfile
import shutil

class MarkdownToPDFConverter:
    def __init__(self):
        self.pandoc_available = self._check_pandoc()
        self.weasyprint_available = self._check_weasyprint()
        self.pdfkit_available = self._check_pdfkit()
        
    def _check_pandoc(self):
        """Check if pandoc is available"""
        try:
            subprocess.run(['pandoc', '--version'], capture_output=True, check=True)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
    
    def _check_weasyprint(self):
        """Check if weasyprint is available"""
        try:
            import weasyprint
            return True
        except (ImportError, OSError) as e:
            # OSError can occur on macOS if system dependencies are missing
            return False
    
    def _check_pdfkit(self):
        """Check if pdfkit and wkhtmltopdf are available"""
        try:
            import pdfkit
            # Check if wkhtmltopdf is installed
            subprocess.run(['wkhtmltopdf', '--version'], capture_output=True, check=True)
            return True
        except (ImportError, subprocess.CalledProcessError, FileNotFoundError):
            return False
    
    def install_dependencies(self):
        """Install required dependencies"""
        print("📦 Installing PDF conversion dependencies...")
        
        # Try to install weasyprint first (pure Python solution)
        try:
            subprocess.run([sys.executable, '-m', 'pip', 'install', 'weasyprint', 'markdown'], check=True)
            print("✅ WeasyPrint installed successfully")
            self.weasyprint_available = True
            return True
        except subprocess.CalledProcessError:
            print("⚠️ WeasyPrint installation failed")
        
        # Fallback to pandoc instructions
        if not self.pandoc_available:
            print("\n📋 To use this converter, install one of the following:")
            print("1. WeasyPrint (Python): pip install weasyprint markdown")
            print("2. Pandoc (System): brew install pandoc (macOS) or apt-get install pandoc (Linux)")
            return False
        
        return True
    
    def convert_with_weasyprint(self, md_file, pdf_file):
        """Convert markdown to PDF using WeasyPrint"""
        try:
            import weasyprint
            import markdown
            
            # Read markdown content
            with open(md_file, 'r', encoding='utf-8') as f:
                md_content = f.read()
            
            # Convert markdown to HTML
            html_content = markdown.markdown(md_content, extensions=['tables', 'fenced_code'])
            
            # Add basic CSS styling
            css_style = """
            <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }
            h1, h2, h3 { color: #2c3e50; }
            h1 { border-bottom: 2px solid #3498db; padding-bottom: 10px; }
            h2 { border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; }
            code {
                background-color: #f8f9fa;
                border: 1px solid #e9ecef;
                border-radius: 3px;
                padding: 2px 4px;
                font-family: 'Monaco', 'Courier New', monospace;
            }
            pre {
                background-color: #f8f9fa;
                border: 1px solid #e9ecef;
                border-radius: 5px;
                padding: 10px;
                overflow-x: auto;
            }
            table {
                border-collapse: collapse;
                width: 100%;
                margin: 10px 0;
            }
            th, td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }
            th { background-color: #f2f2f2; }
            blockquote {
                border-left: 4px solid #3498db;
                margin: 0;
                padding-left: 15px;
                color: #666;
            }
            hr { border: none; border-top: 1px solid #ccc; margin: 20px 0; }
            </style>
            """
            
            # Combine CSS and HTML
            full_html = f"<!DOCTYPE html><html><head>{css_style}</head><body>{html_content}</body></html>"
            
            # Convert to PDF
            weasyprint.HTML(string=full_html).write_pdf(pdf_file)
            return True
            
        except Exception as e:
            print(f"❌ WeasyPrint conversion failed: {e}")
            return False
    
    def convert_with_pandoc(self, md_file, pdf_file):
        """Convert markdown to PDF using Pandoc"""
        try:
            cmd = [
                'pandoc',
                str(md_file),
                '-o', str(pdf_file),
                '--pdf-engine=xelatex',  # or wkhtmltopdf
                '-V', 'geometry:margin=1in',
                '-V', 'fontsize=11pt',
                '--highlight-style=tango'
            ]
            
            subprocess.run(cmd, check=True, capture_output=True)
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Pandoc conversion failed: {e}")
            return False
    
    def convert_single_file(self, md_file, output_dir=None, custom_name=None):
        """Convert a single markdown file to PDF"""
        md_path = Path(md_file)
        
        if not md_path.exists():
            print(f"❌ File not found: {md_file}")
            return False
        
        # Determine output path
        if output_dir:
            output_path = Path(output_dir)
        else:
            output_path = md_path.parent / 'pdf_exports'
        
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Generate PDF filename
        if custom_name:
            pdf_name = f"{custom_name}.pdf"
        else:
            pdf_name = md_path.stem + ".pdf"
        
        pdf_file = output_path / pdf_name
        
        print(f"📄 Converting: {md_path.name} -> {pdf_name}")
        
        # Try conversion methods in order of preference
        success = False
        
        if self.weasyprint_available:
            success = self.convert_with_weasyprint(md_path, pdf_file)
        
        if not success and self.pandoc_available:
            success = self.convert_with_pandoc(md_path, pdf_file)
        
        if success:
            print(f"✅ PDF created: {pdf_file}")
            return pdf_file
        else:
            print(f"❌ Conversion failed for {md_path.name}")
            return False
    
    def convert_directory(self, directory, pattern="*.md", output_dir=None):
        """Convert all markdown files in a directory"""
        dir_path = Path(directory)
        
        if not dir_path.exists():
            print(f"❌ Directory not found: {directory}")
            return []
        
        md_files = list(dir_path.glob(pattern))
        
        if not md_files:
            print(f"❌ No markdown files found in {directory}")
            return []
        
        print(f"📁 Found {len(md_files)} markdown files in {directory}")
        
        converted_files = []
        for md_file in md_files:
            pdf_file = self.convert_single_file(md_file, output_dir)
            if pdf_file:
                converted_files.append(pdf_file)
        
        print(f"\n✅ Converted {len(converted_files)}/{len(md_files)} files successfully")
        return converted_files
    
    def batch_convert_podcast_content(self, base_dir=None):
        """Convert all podcast-related markdown files to PDF"""
        if not base_dir:
            base_dir = Path(__file__).parent.parent
        else:
            base_dir = Path(base_dir)
        
        print("🎙️ Batch converting podcast content to PDF...")
        
        # Define content directories to convert
        content_dirs = {
            'master_transcripts': base_dir / 'content' / 'master_transcripts_organized',
            'wsj_filtered': base_dir / 'content' / 'wsj_filtered',
            'canary_media': base_dir / 'content' / 'canary_media',
            'master_files': base_dir / 'podcast_files' / 'master_files',
            'daily_reports': base_dir / 'scripts' / 'podcast_files' / 'daily_reports'
        }
        
        # Create main PDF output directory
        pdf_output_base = base_dir / 'content' / 'pdf_exports'
        pdf_output_base.mkdir(parents=True, exist_ok=True)
        
        all_converted = []
        
        for content_type, content_dir in content_dirs.items():
            if content_dir.exists():
                print(f"\n📂 Processing {content_type}...")
                
                # Create subdirectory for this content type
                output_subdir = pdf_output_base / content_type
                
                converted_files = self.convert_directory(content_dir, "*.md", output_subdir)
                all_converted.extend(converted_files)
            else:
                print(f"⚠️ Directory not found: {content_dir}")
        
        # Generate summary report
        self._generate_conversion_report(all_converted, pdf_output_base)
        
        return all_converted
    
    def _generate_conversion_report(self, converted_files, output_dir):
        """Generate a summary report of converted files"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        report_file = output_dir / f'conversion_report_{timestamp}.md'
        
        report_content = f"""# PDF Conversion Report
Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
Total Files Converted: {len(converted_files)}

## Converted Files

"""
        
        for pdf_file in converted_files:
            pdf_path = Path(pdf_file)
            file_size = pdf_path.stat().st_size / 1024  # KB
            report_content += f"- **{pdf_path.name}** ({file_size:.1f} KB)\n"
            report_content += f"  - Path: `{pdf_path.relative_to(output_dir.parent)}`\n\n"
        
        report_content += f"""
## Usage

All PDF files have been organized in the following structure:
- `content/pdf_exports/master_transcripts/` - Organized podcast transcripts
- `content/pdf_exports/wsj_filtered/` - WSJ investment analysis
- `content/pdf_exports/canary_media/` - Canary Media analysis  
- `content/pdf_exports/master_files/` - Complete transcript and analysis files
- `content/pdf_exports/daily_reports/` - Daily status reports

## Next Steps

You can now:
1. Email PDF reports directly from the automation system
2. Upload PDFs to Google Drive alongside markdown files
3. Archive older PDF versions as needed
"""
        
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        print(f"\n📋 Conversion report saved: {report_file}")


def main():
    parser = argparse.ArgumentParser(description='Convert markdown files to PDF')
    parser.add_argument('--file', '-f', help='Convert single markdown file')
    parser.add_argument('--directory', '-d', help='Convert all markdown files in directory')
    parser.add_argument('--output', '-o', help='Output directory for PDF files')
    parser.add_argument('--batch', '-b', action='store_true', 
                       help='Batch convert all podcast content')
    parser.add_argument('--install', action='store_true', 
                       help='Install required dependencies')
    parser.add_argument('--name', '-n', help='Custom name for PDF file (single file mode)')
    
    args = parser.parse_args()
    
    converter = MarkdownToPDFConverter()
    
    # Install dependencies if requested
    if args.install:
        success = converter.install_dependencies()
        if not success:
            return 1
    
    # Check if conversion tools are available
    if not converter.weasyprint_available and not converter.pandoc_available:
        print("❌ No PDF conversion tools available!")
        print("Run with --install to install dependencies, or install pandoc manually.")
        return 1
    
    # Perform conversions based on arguments
    if args.batch:
        converted_files = converter.batch_convert_podcast_content()
        print(f"\n🎉 Batch conversion complete! {len(converted_files)} PDFs generated.")
        
    elif args.file:
        pdf_file = converter.convert_single_file(args.file, args.output, args.name)
        if pdf_file:
            print(f"🎉 Conversion complete! PDF: {pdf_file}")
        else:
            return 1
            
    elif args.directory:
        converted_files = converter.convert_directory(args.directory, "*.md", args.output)
        print(f"🎉 Directory conversion complete! {len(converted_files)} PDFs generated.")
        
    else:
        print("📋 Markdown to PDF Converter")
        print("Usage examples:")
        print("  python md_to_pdf_converter.py --batch                    # Convert all podcast content")
        print("  python md_to_pdf_converter.py --file report.md           # Convert single file")
        print("  python md_to_pdf_converter.py --directory content/wsj/   # Convert directory")
        print("  python md_to_pdf_converter.py --install                  # Install dependencies")
        
        return 0

if __name__ == "__main__":
    sys.exit(main())